"""user profile fields + api_key (Registration & Organization Management)

Revision ID: 1be0295e6dbe
Revises: 4ec561b51e64
Create Date: 2026-07-28 16:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1be0295e6dbe'
down_revision: Union[str, Sequence[str], None] = '4ec561b51e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-written, not autogenerated: an auto-generated personal API key
    # (accounts/store.py's own docstring covers why it isn't an enforced
    # credential yet) plus profile fields the registration/profile UI
    # needs (timezone, preferred AI model, default branch naming
    # convention, notification preferences). Every existing row backfills
    # to NULL -- correct for every user created before these existed.
    op.add_column('users', sa.Column('api_key', sa.String(), nullable=True))
    op.create_unique_constraint('uq_users_api_key', 'users', ['api_key'])
    op.add_column('users', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('preferred_ai_model', sa.String(), nullable=True))
    op.add_column('users', sa.Column('default_branch_prefix', sa.String(), nullable=True))
    op.add_column('users', sa.Column('notification_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('users', 'notification_preferences')
    op.drop_column('users', 'default_branch_prefix')
    op.drop_column('users', 'preferred_ai_model')
    op.drop_column('users', 'timezone')
    op.drop_constraint('uq_users_api_key', 'users', type_='unique')
    op.drop_column('users', 'api_key')
