"""initial market_data schema

Revision ID: 34e857120713
Revises: 
Create Date: 2026-07-27 19:05:09.470591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from futures_bot.db.schema import HYPERTABLE_STATEMENTS

# revision identifiers, used by Alembic.
revision: str = '34e857120713'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_contracts',
    sa.Column('product_code', sa.String(), nullable=False),
    sa.Column('contract', sa.String(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('product_code')
    )
    op.create_table('bars',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('product_code', sa.String(), nullable=False),
    sa.Column('contract', sa.String(), nullable=False),
    sa.Column('resolution', sa.String(), nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(), nullable=False),
    sa.Column('high', sa.Numeric(), nullable=False),
    sa.Column('low', sa.Numeric(), nullable=False),
    sa.Column('close', sa.Numeric(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.UniqueConstraint('product_code', 'resolution', 'timestamp', name='uq_bars_identity')
    )
    op.create_index('idx_bars_contract', 'bars', ['contract'], unique=False)
    op.create_table('contract_rolls',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_code', sa.String(), nullable=False),
    sa.Column('from_contract', sa.String(), nullable=True),
    sa.Column('to_contract', sa.String(), nullable=False),
    sa.Column('rolled_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contract_rolls_product', 'contract_rolls', ['product_code'], unique=False)
    op.create_table('gaps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_code', sa.String(), nullable=False),
    sa.Column('resolution', sa.String(), nullable=False),
    sa.Column('gap_start', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('gap_end', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gaps_product', 'gaps', ['product_code', 'resolution'], unique=False)
    op.create_table('sync_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('product_code', sa.String(), nullable=False),
    sa.Column('resolution', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('requested_start', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('requested_end', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('bars_fetched', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_committed_through', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sync_runs_product', 'sync_runs', ['product_code', 'resolution', 'started_at'], unique=False)
    # ### end Alembic commands ###

    # Hypertable conversion (TimescaleDB extension function, not plain DDL
    # SQLAlchemy Core can express -- see db/schema.py::HYPERTABLE_STATEMENTS).
    # Must run after 'bars' exists; `if_not_exists => TRUE` makes this safe
    # to re-run if this revision is ever partially re-applied.
    for statement in HYPERTABLE_STATEMENTS:
        op.execute(statement)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sync_runs_product', table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_index('idx_gaps_product', table_name='gaps')
    op.drop_table('gaps')
    op.drop_index('idx_contract_rolls_product', table_name='contract_rolls')
    op.drop_table('contract_rolls')
    op.drop_index('idx_bars_contract', table_name='bars')
    op.drop_table('bars')
    op.drop_table('active_contracts')
    # ### end Alembic commands ###
