"""research.db schema

Revision ID: 49e936795afa
Revises: 34e857120713
Create Date: 2026-07-27 19:27:07.603231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49e936795afa'
down_revision: Union[str, Sequence[str], None] = '34e857120713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_import_fills',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('fill_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('raw_row', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('import_id', sa.String(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'fingerprint', name='uq_client_import_fills_profile_fingerprint')
    )
    op.create_index('idx_client_import_fills_profile', 'client_import_fills', ['profile_id'], unique=False)
    op.create_table('client_open_lots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('quantity_remaining', sa.Numeric(), nullable=False),
    sa.Column('entry_price', sa.Numeric(), nullable=False),
    sa.Column('entry_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('entry_fingerprint', sa.String(), nullable=False),
    sa.Column('raw_entry_row', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_client_open_lots_profile_symbol', 'client_open_lots', ['profile_id', 'symbol', 'entry_time'], unique=False)
    op.create_table('client_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('config_deployments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('backup_path', sa.String(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_config_deployments_strategy', 'config_deployments', ['strategy', 'created_at'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hypothesis', sa.String(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('dataset', sa.String(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('dataset_version', sa.String(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_experiments_strategy', 'experiments', ['strategy'], unique=False)
    op.create_table('import_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('detected_format', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_fill_rows', sa.Integer(), nullable=False),
    sa.Column('imported_fill_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_fill_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('trades_created', sa.Integer(), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_import_history_profile', 'import_history', ['profile_id', 'created_at'], unique=False)
    op.create_table('import_staging',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('stored_path', sa.String(), nullable=False),
    sa.Column('detected_format', sa.String(), nullable=False),
    sa.Column('suggested_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress_current', sa.Integer(), server_default='0', nullable=False),
    sa.Column('progress_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('progress_message', sa.String(), nullable=True),
    sa.Column('request', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_id', sa.String(), nullable=True),
    sa.Column('result_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_jobs_created_at', 'jobs', ['created_at'], unique=False)
    op.create_index('idx_jobs_status', 'jobs', ['status'], unique=False)
    op.create_table('ml_models',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_family', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('feature_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evaluation_mode', sa.String(), nullable=False),
    sa.Column('dataset_size', sa.Integer(), nullable=False),
    sa.Column('dataset_version', sa.String(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feature_importance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('overfit_warning', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('overfit_note', sa.String(), nullable=True),
    sa.Column('derived_backtest_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('artifact_path', sa.String(), nullable=True),
    sa.Column('app_version', sa.String(), nullable=True),
    sa.Column('git_commit', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ml_models_family', 'ml_models', ['model_family'], unique=False)
    op.create_index('idx_ml_models_strategy', 'ml_models', ['strategy'], unique=False)
    op.create_table('model_deployments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_model_deployments_strategy', 'model_deployments', ['strategy', 'created_at'], unique=False)
    op.create_table('optimization_trials',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('combo_key', sa.String(), nullable=True),
    sa.Column('train_trades', sa.Integer(), nullable=False),
    sa.Column('train_net_pnl', sa.Numeric(), nullable=False),
    sa.Column('train_profit_factor', sa.Numeric(), nullable=True),
    sa.Column('train_max_drawdown', sa.Numeric(), nullable=False),
    sa.Column('train_gross_losses', sa.Numeric(), nullable=True),
    sa.Column('train_win_count', sa.Integer(), nullable=True),
    sa.Column('train_largest_win', sa.Numeric(), nullable=True),
    sa.Column('validation_trades', sa.Integer(), nullable=True),
    sa.Column('validation_net_pnl', sa.Numeric(), nullable=True),
    sa.Column('validation_profit_factor', sa.Numeric(), nullable=True),
    sa.Column('validation_max_drawdown', sa.Numeric(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'combo_key', name='uq_trials_batch_combo')
    )
    op.create_index('idx_trials_batch_id', 'optimization_trials', ['batch_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reports_run_id', 'reports', ['run_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('contract', sa.String(), nullable=False),
    sa.Column('strategy_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('csv_path', sa.String(), nullable=True),
    sa.Column('walk_forward', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('starting_equity', sa.Numeric(), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.Column('net_pnl', sa.Numeric(), nullable=True),
    sa.Column('profit_factor', sa.Numeric(), nullable=True),
    sa.Column('win_rate', sa.Numeric(), nullable=True),
    sa.Column('expectancy', sa.Numeric(), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(), nullable=True),
    sa.Column('sortino_ratio', sa.Numeric(), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(), nullable=True),
    sa.Column('max_drawdown_pct', sa.Numeric(), nullable=True),
    sa.Column('validation_trade_count', sa.Integer(), nullable=True),
    sa.Column('validation_net_pnl', sa.Numeric(), nullable=True),
    sa.Column('validation_profit_factor', sa.Numeric(), nullable=True),
    sa.Column('caveats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_bar', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_bar', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_runs_created_at', 'runs', ['created_at'], unique=False)
    op.create_index('idx_runs_strategy', 'runs', ['strategy'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('contract', sa.String(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('strategy_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('entry_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('exit_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('entry_price', sa.Numeric(), nullable=False),
    sa.Column('exit_price', sa.Numeric(), nullable=False),
    sa.Column('gross_pnl', sa.Numeric(), nullable=False),
    sa.Column('commission', sa.Numeric(), nullable=False),
    sa.Column('net_pnl', sa.Numeric(), nullable=False),
    sa.Column('holding_minutes', sa.Numeric(), nullable=False),
    sa.Column('exit_reason', sa.String(), nullable=False),
    sa.Column('session_date', sa.String(), nullable=False),
    sa.Column('day_of_week', sa.String(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('entry_reason', sa.String(), nullable=False),
    sa.Column('entry_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('mfe_points', sa.Numeric(), nullable=True),
    sa.Column('mae_points', sa.Numeric(), nullable=True),
    sa.Column('efficiency', sa.Numeric(), nullable=True),
    sa.Column('regime_trend', sa.String(), nullable=True),
    sa.Column('regime_volatility', sa.String(), nullable=True),
    sa.Column('regime_session', sa.String(), nullable=True),
    sa.Column('trade_id', sa.String(), nullable=True),
    sa.Column('stop_loss', sa.Numeric(), nullable=True),
    sa.Column('take_profit', sa.Numeric(), nullable=True),
    sa.Column('entry_slippage', sa.Numeric(), nullable=True),
    sa.Column('exit_slippage', sa.Numeric(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id', name='uq_trades_trade_id')
    )
    op.create_index('idx_trades_run_id', 'trades', ['run_id'], unique=False)
    op.create_index('idx_trades_session_date', 'trades', ['session_date'], unique=False)
    op.create_index('idx_trades_strategy', 'trades', ['strategy'], unique=False)
    # NOTE: autogenerate also detected a "removed index" 'bars_timestamp_idx'
    # on `bars` and emitted `op.drop_index(...)` for it here -- removed by
    # hand. That index is TimescaleDB's own internal hypertable-chunk index
    # (created automatically by `create_hypertable()` in the prior revision,
    # not something SQLAlchemy's `Table` definition in db/schema.py knows
    # about), not a real schema drift on `bars`. Dropping it would degrade
    # the already-verified `bars` hypertable this revision has nothing to
    # do with.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # (see the matching NOTE in upgrade() -- bars_timestamp_idx is left alone)
    op.drop_index('idx_trades_strategy', table_name='trades')
    op.drop_index('idx_trades_session_date', table_name='trades')
    op.drop_index('idx_trades_run_id', table_name='trades')
    op.drop_table('trades')
    op.drop_index('idx_runs_strategy', table_name='runs')
    op.drop_index('idx_runs_created_at', table_name='runs')
    op.drop_table('runs')
    op.drop_index('idx_reports_run_id', table_name='reports')
    op.drop_table('reports')
    op.drop_index('idx_trials_batch_id', table_name='optimization_trials')
    op.drop_table('optimization_trials')
    op.drop_index('idx_model_deployments_strategy', table_name='model_deployments')
    op.drop_table('model_deployments')
    op.drop_index('idx_ml_models_strategy', table_name='ml_models')
    op.drop_index('idx_ml_models_family', table_name='ml_models')
    op.drop_table('ml_models')
    op.drop_index('idx_jobs_status', table_name='jobs')
    op.drop_index('idx_jobs_created_at', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('import_staging')
    op.drop_index('idx_import_history_profile', table_name='import_history')
    op.drop_table('import_history')
    op.drop_index('idx_experiments_strategy', table_name='experiments')
    op.drop_table('experiments')
    op.drop_index('idx_config_deployments_strategy', table_name='config_deployments')
    op.drop_table('config_deployments')
    op.drop_table('client_profiles')
    op.drop_index('idx_client_open_lots_profile_symbol', table_name='client_open_lots')
    op.drop_table('client_open_lots')
    op.drop_index('idx_client_import_fills_profile', table_name='client_import_fills')
    op.drop_table('client_import_fills')
    # ### end Alembic commands ###
