"""work_items.owner_type (SIL Phase 2: Workflow Integration)

Revision ID: 4ec561b51e64
Revises: d27c59fb1500
Create Date: 2026-07-28 15:05:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4ec561b51e64'
down_revision: Union[str, Sequence[str], None] = 'd27c59fb1500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-written, not autogenerated: distinguishes an AI-claimed work item
    # from a human's for Mission Control's "AI Workers" view and the
    # pre-work-check's coordination advice (collaboration/__init__.py's
    # OWNER_TYPES). Every existing row backfills to 'human' via the column
    # default -- correct for every work item created before this existed.
    op.add_column('work_items', sa.Column('owner_type', sa.String(), server_default='human', nullable=False))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('work_items', 'owner_type')
