"""bars.created_at nullable (ISSUE-004 real data has NULLs)

Revision ID: 66fd84a1c6cb
Revises: 49e936795afa
Create Date: 2026-07-28 07:08:39.467625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66fd84a1c6cb'
down_revision: Union[str, Sequence[str], None] = '49e936795afa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # bars.created_at only -- NOT the accompanying autogenerated
    # `drop_index('bars_timestamp_idx')`: that index is TimescaleDB's own,
    # created automatically by create_hypertable() on the time dimension,
    # not something declared in schema.py's metadata at all. Autogenerate
    # diffed it as "removed" purely because our model never declared it in
    # the first place -- dropping it for real would hurt every time-range
    # query's chunk exclusion. See ISSUE-004/PROJECT_STATE.md for why this
    # column needs to be nullable: 32.5% of real bars rows have NULL
    # created_at, a pre-existing SQLite schema-drift issue.
    op.alter_column('bars', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))


def downgrade() -> None:
    """Downgrade schema."""
    op.alter_column('bars', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
