"""workers table (SIL Phase 6 Integration Coordinator Milestone 1)

Revision ID: 6794ec903e7c
Revises: bb0017abe70b
Create Date: 2026-07-29 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6794ec903e7c'
down_revision: Union[str, Sequence[str], None] = 'bb0017abe70b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-written, not autogenerated -- see collaboration/store.py's
    # matching SQLite schema for the full rationale: id is
    # caller-supplied (not server-minted), current_work_item_id/user_id/
    # org_id are soft references (no FK, matching work_items.owner_user_id's
    # own precedent), capabilities is JSONB (a list of free-form tags,
    # matching estimated_files' existing JSONB precedent), and staleness
    # is always computed live from last_heartbeat_at -- never a stored
    # column here.
    op.create_table('workers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('worker_type', sa.String(), server_default='ai_agent', nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='online', nullable=False),
    sa.Column('current_work_item_id', sa.String(), nullable=True),
    sa.Column('subsystem', sa.String(), nullable=True),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('last_heartbeat_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workers_org_id', 'workers', ['org_id'], unique=False)
    op.create_index('idx_workers_status', 'workers', ['status'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('idx_workers_status', table_name='workers')
    op.drop_index('idx_workers_org_id', table_name='workers')
    op.drop_table('workers')
