"""work_items.is_draft (SIL Phase 4: Intelligent Automation Layer)

Revision ID: 7a3f9c2e1b0d
Revises: 9f68d758839f
Create Date: 2026-07-29 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7a3f9c2e1b0d'
down_revision: Union[str, Sequence[str], None] = '9f68d758839f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-written, not autogenerated: marks a work item as auto-created by
    # the SIL Phase 4 background git-watcher, pending explicit human/AI
    # review (approve clears this flag; discard hard-deletes the row --
    # see collaboration/store.py's module docstring on _WORK_ITEM_COLLABORATION_COLUMNS).
    # Every existing row backfills to false via the column default -- every
    # work item created before this existed was a real (non-draft) item.
    op.add_column('work_items', sa.Column('is_draft', sa.Boolean(), server_default='false', nullable=False))
    op.create_index('idx_work_items_is_draft', 'work_items', ['is_draft'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('idx_work_items_is_draft', table_name='work_items')
    op.drop_column('work_items', 'is_draft')
