"""user/organization accounts (Team Collaboration MVP)

Revision ID: 91f82e2b91f2
Revises: 66fd84a1c6cb
Create Date: 2026-07-28 14:06:55.478109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91f82e2b91f2'
down_revision: Union[str, Sequence[str], None] = '66fd84a1c6cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Note: the autogenerated diff also proposed dropping bars_timestamp_idx
    # -- deliberately excluded, same as the previous revision (66fd84a1c6cb):
    # that index is TimescaleDB's own, created automatically by
    # create_hypertable() on the time dimension, never declared in
    # db/schema.py's metadata, and dropping it for real would hurt every
    # time-range query's chunk exclusion.
    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_users_org_id', 'users', ['org_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('idx_users_org_id', table_name='users')
    op.drop_table('users')
    op.drop_table('organizations')
