"""work_items.org_id (Registration & Organization Management)

Revision ID: 9f68d758839f
Revises: 1be0295e6dbe
Create Date: 2026-07-28 16:35:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9f68d758839f'
down_revision: Union[str, Sequence[str], None] = '1be0295e6dbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-written, not autogenerated: nullable, no FK constraint (matches
    # work_items.owner_user_id's own precedent -- an informal reference,
    # not enforced, same reasoning as that column). A work item created
    # before organizations existed, or by a session-less caller (the CLI),
    # simply has org_id=NULL -- unscoped, visible regardless of which org
    # is asking (see collaboration/store.py::fetch_work_items's docstring).
    op.add_column('work_items', sa.Column('org_id', sa.String(), nullable=True))
    op.create_index('idx_work_items_org_id', 'work_items', ['org_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('idx_work_items_org_id', table_name='work_items')
    op.drop_column('work_items', 'org_id')
