"""integration_reviews table (SIL Phase 6 Integration Coordinator Milestone 2)

Revision ID: b91531ca7583
Revises: 6794ec903e7c
Create Date: 2026-07-29 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b91531ca7583'
down_revision: Union[str, Sequence[str], None] = '6794ec903e7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-written, not autogenerated -- see collaboration/store.py's
    # matching SQLite schema comment for the full rationale: append-only
    # (no update/delete path exists anywhere in this codebase for this
    # table), work_item_id is a soft reference (no ForeignKey, matching
    # work_item_activity's own Postgres definition), and four JSONB
    # columns mirror workers.capabilities' existing precedent.
    op.create_table('integration_reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('work_item_id', sa.String(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('status_at_review', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('related_work_item_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('affected_subsystems', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('conflict_resolutions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('validation_recommendation', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('readiness_note', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('recommendation', sa.String(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_integration_reviews_work_item', 'integration_reviews', ['work_item_id', 'created_at'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('idx_integration_reviews_work_item', table_name='integration_reviews')
    op.drop_table('integration_reviews')
