"""active work registry (Team Collaboration MVP)

Revision ID: d27c59fb1500
Revises: 91f82e2b91f2
Create Date: 2026-07-28 14:28:45.732262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd27c59fb1500'
down_revision: Union[str, Sequence[str], None] = '91f82e2b91f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Note: the autogenerated diff also proposed dropping bars_timestamp_idx
    # -- deliberately excluded, same as every previous revision touching
    # this database (66fd84a1c6cb, 91f82e2b91f2): that index is
    # TimescaleDB's own, created automatically by create_hypertable() on
    # the time dimension, never declared in db/schema.py's metadata, and
    # dropping it for real would hurt every time-range query's chunk
    # exclusion.
    op.create_table('work_item_activity',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('work_item_id', sa.String(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('actor_user_id', sa.String(), nullable=True),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_work_item_activity_item', 'work_item_activity', ['work_item_id', 'created_at'], unique=False)
    op.create_table('work_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='open', nullable=False),
    sa.Column('estimated_files', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('priority', sa.String(), server_default='medium', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_work_items_status', 'work_items', ['status'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('idx_work_items_status', table_name='work_items')
    op.drop_table('work_items')
    op.drop_index('idx_work_item_activity_item', table_name='work_item_activity')
    op.drop_table('work_item_activity')
    # ### end Alembic commands ###
