"""SQLAlchemy Core table definitions for TimescaleDB/Postgres.

**Verified against a real Postgres/TimescaleDB server** (2026-07-27):
`alembic upgrade head` against the `deploy/docker-compose.yml`
`timescaledb` service creates all 5 tables and converts `bars` into a
real hypertable (`timescaledb_information.hypertables` confirmed);
`tests/test_pg_market_data_store_live.py` (10 tests) exercises every
`PgMarketDataStore` method against it. One real bug found and fixed by
this verification: `bars.id` needs `Identity()`, not bare
`autoincrement=True` -- see that column's own comment below for why.

Defines the same tables as `market_data/store.py`'s `_SCHEMA` string,
translated to Postgres types (`NUMERIC`/`TIMESTAMPTZ` instead of TEXT-
encoded Decimal/ISO strings, `BIGSERIAL` instead of `INTEGER AUTOINCREMENT`)
via SQLAlchemy Core `Table`/`MetaData` objects rather than a raw SQL
string, specifically so Alembic (`../../alembic/`) can autogenerate
migration diffs against it. Nothing here is an ORM model -- these
`Table` objects are only ever used for their `CREATE TABLE` DDL and by
Alembic; `pg_store.py` still writes plain parameterized SQL via
`sqlalchemy.text()`/Core `insert()`/`select()` constructs, matching this
project's existing plain-SQL style.

**research.db's 15 tables are not defined here yet** -- this migration
started with `market_data.db` (5 tables) to prove the whole pattern
(schema -> pooled store -> factory seam -> migration -> health check)
end to end on the smaller of the two databases first. Porting
`research/trade_store.py`'s schema follows the identical pattern once
this one is verified against a real server.
"""

from __future__ import annotations

from sqlalchemy import (
    BigInteger,
    Column,
    Identity,
    Index,
    MetaData,
    Numeric,
    String,
    Table,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import TIMESTAMP

metadata = MetaData()

# `TIMESTAMP(timezone=True)` -- Postgres `TIMESTAMPTZ`. Every timestamp in
# this app is already timezone-aware (models.Bar.timestamp, etc.); this
# is the native equivalent of the SQLite schema's "ISO 8601, UTC" TEXT
# convention, not a behavior change.
_TSTZ = TIMESTAMP(timezone=True)

#: One row per (product, resolution, timestamp) -- see
#: market_data/store.py's module docstring for why `contract` is *not*
#: part of the identity. `id` stays as a plain BIGSERIAL column, not the
#: primary key: TimescaleDB requires every unique constraint on a
#: hypertable to include the partitioning column (`timestamp`), so the
#: real identity constraint below (`uq_bars_identity`, matching the
#: original `idx_bars_identity` unique index exactly) is what's actually
#: enforced -- `id` exists only as a stable row handle, same role it
#: played in SQLite.
#:
#: `Identity()` (not bare `autoincrement=True`) is required here: Postgres
#: only auto-generates a sequence default for `autoincrement=True` when the
#: column is a single-column primary key, which `id` deliberately is not
#: (see above). Without `Identity()`, `pg_store.py::upsert_bars` -- which
#: never supplies `id` itself, exactly like the SQLite store never did --
#: would hit a `NOT NULL` violation on its very first insert. Found and
#: fixed during this schema's first real verification against a live
#: server (see PROJECT_STATE.md); `GENERATED BY DEFAULT AS IDENTITY` (not
#: `ALWAYS`) so a future data-migration script can still explicitly supply
#: `id` values when copying rows from SQLite, if that's ever needed.
bars = Table(
    "bars",
    metadata,
    Column("id", BigInteger, Identity(always=False), nullable=False),
    Column("product_code", String, nullable=False),
    Column("contract", String, nullable=False),
    Column("resolution", String, nullable=False),
    Column("timestamp", _TSTZ, nullable=False),
    Column("open", Numeric, nullable=False),
    Column("high", Numeric, nullable=False),
    Column("low", Numeric, nullable=False),
    Column("close", Numeric, nullable=False),
    Column("volume", BigInteger, nullable=False),
    Column("source", String, nullable=False),
    # Nullable, not NOT NULL: the SQLite source (KNOWN_ISSUES.md ISSUE-004)
    # declares this column NOT NULL DEFAULT but the live table predates that
    # revision and was never migrated -- 32.5% of real bars rows (every
    # source, not an edge case) genuinely have no created_at. A NOT NULL
    # constraint here would reject real production data outright (confirmed
    # the hard way: tools/migrate_to_timescaledb.py's first live run against
    # real data raised NotNullViolation partway through). New inserts still
    # get one via server_default.
    Column("created_at", _TSTZ, nullable=True, server_default=func.now()),
    UniqueConstraint("product_code", "resolution", "timestamp", name="uq_bars_identity"),
    Index("idx_bars_contract", "contract"),
)

sync_runs = Table(
    "sync_runs",
    metadata,
    Column("id", String, primary_key=True),
    Column("product_code", String, nullable=False),
    Column("resolution", String, nullable=False),
    Column("kind", String, nullable=False),
    Column("status", String, nullable=False),
    Column("requested_start", _TSTZ),
    Column("requested_end", _TSTZ),
    Column("bars_fetched", BigInteger, nullable=False, server_default=text("0")),
    Column("last_committed_through", _TSTZ),
    Column("error_message", String),
    Column("started_at", _TSTZ, nullable=False, server_default=func.now()),
    Column("completed_at", _TSTZ),
    Index("idx_sync_runs_product", "product_code", "resolution", "started_at"),
)

gaps = Table(
    "gaps",
    metadata,
    Column("id", BigInteger, primary_key=True, autoincrement=True),
    Column("product_code", String, nullable=False),
    Column("resolution", String, nullable=False),
    Column("gap_start", _TSTZ, nullable=False),
    Column("gap_end", _TSTZ, nullable=False),
    Column("detected_at", _TSTZ, nullable=False, server_default=func.now()),
    Column("resolved_at", _TSTZ),
    Index("idx_gaps_product", "product_code", "resolution"),
)

active_contracts = Table(
    "active_contracts",
    metadata,
    Column("product_code", String, primary_key=True),
    Column("contract", String, nullable=False),
    Column("updated_at", _TSTZ, nullable=False, server_default=func.now()),
)

contract_rolls = Table(
    "contract_rolls",
    metadata,
    Column("id", BigInteger, primary_key=True, autoincrement=True),
    Column("product_code", String, nullable=False),
    Column("from_contract", String),
    Column("to_contract", String, nullable=False),
    Column("rolled_at", _TSTZ, nullable=False, server_default=func.now()),
    Index("idx_contract_rolls_product", "product_code"),
)

#: Statements run once, after `metadata.create_all()`, to convert `bars`
#: into a TimescaleDB hypertable -- `create_hypertable` is a TimescaleDB
#: extension function, not plain DDL SQLAlchemy can express, so this
#: stays a raw SQL string executed separately (see the initial Alembic
#: revision). `if_not_exists => TRUE` makes re-running this safe.
HYPERTABLE_STATEMENTS = (
    "CREATE EXTENSION IF NOT EXISTS timescaledb",
    "SELECT create_hypertable('bars', 'timestamp', if_not_exists => TRUE)",
)
