"""SIL Phase 4's "Automatic Documentation Assistance": drafts a
CHANGELOG.md-style entry from what's happened since CHANGELOG.md was last
updated -- every commit in that window, plus every work item that reached
`completed`/`merged` in it -- and writes it to a scratch file for a human
(or an AI-assisted session) to review, rewrite into this repo's narrative
prose style, and paste into the real CHANGELOG.md by hand.

Never edits CHANGELOG.md itself -- CLAUDE.md's Session Protocol makes
that a human/session judgment call (what actually matters, what's a
breaking change, what commit hash to cite), not something to automate
away. This only saves the "what happened since last time" gathering step.

Usage:

    python tools/draft_changelog.py                    # writes .changelog_draft.md
    python tools/draft_changelog.py --out somewhere.md  # write elsewhere
    python tools/draft_changelog.py --print             # also print to stdout
"""

from __future__ import annotations

import argparse
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Optional

from futures_bot.collaboration import git_info, parse_db_timestamp
from futures_bot.collaboration.store import get_collaboration_store

_DEFAULT_OUT = ".changelog_draft.md"
_CHANGELOG_PATH = "CHANGELOG.md"
_DONE_STATUSES = ("completed", "merged")


def _boundary() -> tuple[Optional[str], Optional[datetime]]:
    """The last commit that touched CHANGELOG.md -- `commits_since`'s
    `ref` and the cutoff for "recently completed" work items. `(None,
    None)` if CHANGELOG.md has no commit history yet (a fresh repo, or
    this script pointed at a fork that dropped it) -- callers treat that
    as "everything is in scope," not as an error."""
    commit = git_info.last_commit_touching(_CHANGELOG_PATH)
    if commit is None or not commit.authored_at:
        return None, None
    try:
        authored_at = datetime.fromisoformat(commit.authored_at)
    except ValueError:
        return commit.hash, None
    return commit.hash, authored_at


def _recently_done_work_items(since: Optional[datetime]) -> list[dict]:
    store = get_collaboration_store()
    items = [i for i in store.fetch_work_items() if i["status"] in _DONE_STATUSES]
    if since is None:
        return items
    since_aware = since if since.tzinfo else since.replace(tzinfo=timezone.utc)
    result = []
    for item in items:
        try:
            updated_at = parse_db_timestamp(item["updated_at"])
        except (ValueError, AttributeError, TypeError):
            continue
        if updated_at >= since_aware:
            result.append(item)
    return result


def build_draft() -> str:
    ref, since = _boundary()
    commits = git_info.commits_since(ref)
    work_items = _recently_done_work_items(since)
    branch_info = git_info.get_branch_info()

    lines: list[str] = []
    lines.append(f"<!-- DRAFT generated by tools/draft_changelog.py on {date.today().isoformat()} -->")
    lines.append(f"<!-- Review and rewrite into narrative prose before pasting into {_CHANGELOG_PATH} -->")
    lines.append("")
    lines.append(f"## {date.today().isoformat()} — <fill in a short summary title>")
    lines.append("")
    if ref:
        lines.append(f"Since CHANGELOG.md was last updated (commit `{ref[:10]}`):")
    else:
        lines.append(f"No prior commit found touching {_CHANGELOG_PATH} -- showing everything on `{branch_info.branch or 'HEAD'}`:")
    lines.append("")

    lines.append(f"### Commits ({len(commits)})")
    lines.append("")
    if commits:
        for c in commits:
            lines.append(f"- `{c.short_hash}` {c.subject} ({c.author})")
    else:
        lines.append("- (none)")
    lines.append("")

    lines.append(f"### Completed/merged work items ({len(work_items)})")
    lines.append("")
    if work_items:
        for item in work_items:
            files = ", ".join(item["estimated_files"][:5]) or "no files recorded"
            lines.append(f"- **{item['title']}** ({item['status']}, {item['owner_type']}) — {files}")
    else:
        lines.append("- (none)")
    lines.append("")

    lines.append("### Scaffolding to fill in by hand (CLAUDE.md's Session Protocol)")
    lines.append("")
    for heading in ("Added", "Changed", "Fixed", "Removed", "DB changes", "API changes", "Frontend changes", "Breaking changes"):
        lines.append(f"- **{heading}:** ")
    lines.append("")

    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--out", default=_DEFAULT_OUT, help=f"Where to write the draft (default: {_DEFAULT_OUT}).")
    parser.add_argument("--print", dest="also_print", action="store_true", help="Also print the draft to stdout.")
    args = parser.parse_args(argv)

    draft = build_draft()
    out_path = Path(args.out)
    out_path.write_text(draft, encoding="utf-8")
    print(f"Draft written to {out_path} -- review and rewrite before pasting into {_CHANGELOG_PATH}.")
    if args.also_print:
        print("\n" + draft)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
