"""One-time (or safe-to-rerun) data migration: copies every row from the
local SQLite `market_data.db`/`research.db` into the shared TimescaleDB/
Postgres instance a team deployment uses instead (see `TEAM_DEPLOYMENT.md`).
Not part of the installable package -- an ops script, same `tools/`
category as `merge_backup_contracts.py`.

Reads directly from the SQLite files via `sqlite3`, opened read-only
(`file:...?mode=ro`) so this can never write to them regardless of a bug
elsewhere in this script -- not through `MarketDataStore`/`TradeStore`'s
own read methods, because those don't expose everything a faithful row-
for-row copy needs. In particular, `MarketDataStore.fetch_bars()`
deliberately can't return `contract`/`source` per row (see that method's
own docstring: multiple contracts can share a `(product_code, resolution)`
history, and the public read API only ever answers "give me this
product+resolution's bars," not "give me this one contract's bars") --
this script needs every column, so it reads the `bars` table directly.

Writes through SQLAlchemy Core `insert(...).on_conflict_do_nothing()`
against `db/schema.py`'s and `db/research_schema.py`'s `Table` objects
directly -- not `PgMarketDataStore`/`PgTradeStore`'s own methods, which
are built for one logical operation at a time, not bulk batch replication,
and at least one (`set_active_contract`) has a side effect (recording a
synthetic contract-roll row on every call) that would corrupt real roll
history if used to replay old rows instead of writing new ones. Every
insert conflicts on each table's real uniqueness constraint, so this is
safe to re-run after a partial failure or to pick up rows written to the
SQLite side after a previous run.

`bars.id` is the one column deliberately never copied: `KNOWN_ISSUES.md`
ISSUE-004 documents that this column is already `NULL` for every row in
the live SQLite database (long-standing schema drift), so there is
nothing meaningful to preserve -- the destination's own `Identity()`
column assigns a fresh id, exactly as it already does for every row
`PgMarketDataStore.upsert_bars` writes today. Every other table's `id`
(a real value either way -- an autoincrement int for `trades`/
`optimization_trials`, a uuid-hex string everywhere else) is preserved
as-is; Postgres's `GENERATED BY DEFAULT AS IDENTITY` (used for the two
integer cases) allows an explicit value to override the sequence.

Usage::

    python tools/migrate_to_timescaledb.py --dry-run
    python tools/migrate_to_timescaledb.py --yes

Back up both `.db` files first regardless of `--dry-run` -- this script
only ever reads from them (enforced at the SQLite connection level, not
just by convention), but see `docs/DATABASE_CORRUPTION_REPORT.md` for why
"only reads" is not the same guarantee as "verified by a backup."
"""

from __future__ import annotations

import argparse
import os
import sqlite3
import sys
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Any, Optional

BATCH_SIZE = 500


def _open_source_readonly(path: Path) -> sqlite3.Connection:
    """Read-only at the SQLite connection level (`mode=ro`), not just by
    convention -- any write attempt against this connection raises
    `sqlite3.OperationalError` immediately, rather than relying on this
    script simply never issuing one."""
    if not path.exists():
        raise FileNotFoundError(f"Source database not found: {path}")
    conn = sqlite3.connect(f"file:{path.as_posix()}?mode=ro", uri=True)
    conn.row_factory = sqlite3.Row
    return conn


def _coerce_value(value: Any, column) -> Any:
    """Converts one SQLite-native value (str/int/None) into whatever
    Python type the *destination* SQLAlchemy column actually expects --
    the SQLite side stores money/JSON/booleans/timestamps all as TEXT/
    INTEGER (see `trade_store.py`/`store.py`'s own module docstrings for
    why), while the Postgres schema uses real `NUMERIC`/`JSONB`/`Boolean`/
    `TIMESTAMPTZ` types that expect real Python `Decimal`/`dict`/`bool`/
    `datetime` objects, not their string/int encodings."""
    import json
    from datetime import datetime

    from sqlalchemy import Boolean, Numeric
    from sqlalchemy.dialects.postgresql import JSONB
    from sqlalchemy.types import TIMESTAMP

    if value is None:
        return None
    col_type = column.type
    if isinstance(col_type, Numeric):
        if isinstance(value, Decimal):
            return value
        try:
            return Decimal(str(value))
        except InvalidOperation:
            return None  # a genuinely malformed source value -- never fabricate a number
    if isinstance(col_type, TIMESTAMP):
        if isinstance(value, str):
            return datetime.fromisoformat(value)
        return value
    if isinstance(col_type, JSONB):
        if isinstance(value, str):
            return json.loads(value)
        return value
    if isinstance(col_type, Boolean):
        if isinstance(value, int):
            return bool(value)
        return value
    return value


def _row_count(conn: sqlite3.Connection, table_name: str) -> int:
    return conn.execute(f"SELECT COUNT(*) FROM {table_name}").fetchone()[0]  # noqa: S608 -- table_name is our own fixed schema list, never user input


def migrate_table(
    source_conn: sqlite3.Connection, dest_engine, table, *, source_table_name: Optional[str] = None,
    exclude_columns: frozenset[str] = frozenset(), dry_run: bool = True,
) -> tuple[int, int]:
    """Copies one table. Returns `(source_row_count, rows_inserted)` --
    `rows_inserted` can be less than the source count on a re-run (rows
    already present conflict and are skipped, by design)."""
    from sqlalchemy.dialects.postgresql import insert as pg_insert

    name = source_table_name or table.name
    total_source = _row_count(source_conn, name)
    if dry_run:
        return total_source, 0

    dest_columns = [c for c in table.columns if c.name not in exclude_columns]
    cursor = source_conn.execute(f"SELECT * FROM {name}")  # noqa: S608 -- fixed schema list, never user input
    inserted = 0
    while True:
        rows = cursor.fetchmany(BATCH_SIZE)
        if not rows:
            break
        batch = [
            {c.name: _coerce_value(row[c.name], c) for c in dest_columns}
            for row in rows
        ]
        stmt = pg_insert(table).values(batch)
        # Every table this script writes has exactly one real uniqueness
        # constraint (its primary key, or -- for `bars` -- `uq_bars_identity`
        # since `id` is excluded here) -- conflicting on the table's own
        # primary key/constraints (SQLAlchemy's default when no
        # `index_elements` is given) is correct in every case.
        # `RETURNING` + `len(fetchall())`, not `result.rowcount` -- the
        # exact same pitfall `pg_store.py::upsert_bars`'s own docstring
        # already documents and avoids: a multi-row `ON CONFLICT DO
        # NOTHING`'s driver-reported `rowcount` is not reliably "rows
        # actually inserted" (confirmed the hard way here -- an early
        # version of this script always reported 0 newly inserted, on
        # every table, even on the very first real run, despite the
        # data landing correctly).
        stmt = stmt.on_conflict_do_nothing().returning(*dest_columns)
        with dest_engine.begin() as conn:
            result = conn.execute(stmt)
            inserted += len(result.fetchall())
    return total_source, inserted


def migrate_market_data(market_data_db_path: Path, dest_engine, *, dry_run: bool) -> dict[str, tuple[int, int]]:
    from futures_bot.db.schema import active_contracts, bars, contract_rolls, gaps, sync_runs

    conn = _open_source_readonly(market_data_db_path)
    try:
        results = {}
        # bars first (the largest table, and the one exclusion) -- id is
        # never copied, see module docstring.
        results["bars"] = migrate_table(conn, dest_engine, bars, exclude_columns=frozenset({"id"}), dry_run=dry_run)
        results["sync_runs"] = migrate_table(conn, dest_engine, sync_runs, dry_run=dry_run)
        results["gaps"] = migrate_table(conn, dest_engine, gaps, dry_run=dry_run)
        results["active_contracts"] = migrate_table(conn, dest_engine, active_contracts, dry_run=dry_run)
        results["contract_rolls"] = migrate_table(conn, dest_engine, contract_rolls, dry_run=dry_run)
        return results
    finally:
        conn.close()


def migrate_research(research_db_path: Path, dest_engine, *, dry_run: bool) -> dict[str, tuple[int, int]]:
    from futures_bot.db.research_schema import (
        client_import_fills, client_open_lots, client_profiles, config_deployments, experiments, import_history,
        import_staging, jobs, ml_models, model_deployments, optimization_trials, reports, runs, trades,
    )

    conn = _open_source_readonly(research_db_path)
    try:
        results = {}
        for table in (
            trades, optimization_trials, runs, reports, jobs, experiments, ml_models, model_deployments,
            client_profiles, import_staging, client_import_fills, client_open_lots, import_history,
            config_deployments,
        ):
            results[table.name] = migrate_table(conn, dest_engine, table, dry_run=dry_run)
        return results
    finally:
        conn.close()


def _print_report(label: str, results: dict[str, tuple[int, int]], *, dry_run: bool) -> None:
    print(f"\n{label}:")
    for table_name, (source_count, inserted) in results.items():
        if dry_run:
            print(f"  {table_name}: {source_count} rows in source (would migrate)")
        else:
            skipped = source_count - inserted
            print(f"  {table_name}: {source_count} in source, {inserted} newly inserted, {skipped} already present")


def _verify_row_counts(source_results: dict[str, tuple[int, int]], dest_engine, table_lookup: dict[str, Any]) -> bool:
    """Source-vs-destination row-count check, run after a real (non-dry-run)
    migration -- same discipline `docs/DATABASE_CORRUPTION_REPORT.md`'s
    turtle-data repair established for this codebase: never trust a
    migration silently, verify counts. A destination count *lower* than
    the source is the only failure condition -- higher is impossible
    (`ON CONFLICT DO NOTHING` never duplicates), and a destination that
    already had rows from a previous run (higher than what THIS run
    inserted, but not lower than source) is expected on a re-run."""
    from sqlalchemy import func, select

    all_ok = True
    for table_name, (source_count, _inserted) in source_results.items():
        table = table_lookup[table_name]
        with dest_engine.connect() as conn:
            dest_count = conn.execute(select(func.count()).select_from(table)).scalar_one()
        ok = dest_count >= source_count
        all_ok = all_ok and ok
        status = "OK" if ok else "MISMATCH"
        print(f"  [{status}] {table_name}: source={source_count}, destination={dest_count}")
    return all_ok


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--yes", action="store_true", help="Actually write to the destination. Without this, nothing is written (dry-run).")
    parser.add_argument("--dry-run", action="store_true", help="Explicit dry-run (also the default with neither flag).")
    parser.add_argument("--market-data-db", type=Path, default=None, help="Source market_data.db path (default: FUTURES_BOT_MARKET_DATA_DB or ./market_data.db)")
    parser.add_argument("--research-db", type=Path, default=None, help="Source research.db path (default: FUTURES_BOT_RESEARCH_DB or ./research.db)")
    parser.add_argument("--skip-market-data", action="store_true", help="Only migrate research.db.")
    parser.add_argument("--skip-research", action="store_true", help="Only migrate market_data.db.")
    args = parser.parse_args(argv)

    if args.yes and args.dry_run:
        print("--yes and --dry-run are mutually exclusive.", file=sys.stderr)
        return 1
    dry_run = not args.yes

    database_url = os.environ.get("FUTURES_BOT_DATABASE_URL")
    if not database_url:
        print("FUTURES_BOT_DATABASE_URL is not set -- nothing to migrate to.", file=sys.stderr)
        return 1

    from futures_bot.db.engine import get_engine
    from futures_bot.market_data.store import default_db_path as default_market_data_db_path
    from futures_bot.research.trade_store import default_db_path as default_research_db_path

    market_data_db_path = args.market_data_db or default_market_data_db_path()
    research_db_path = args.research_db or default_research_db_path()

    dest_engine = get_engine()

    if dry_run:
        print("DRY RUN -- nothing will be written. Pass --yes to actually migrate.")
    else:
        # Ensure the destination schema exists before writing to it --
        # idempotent, matches PgMarketDataStore/PgTradeStore.ensure_schema()'s
        # own "creates what's missing, never alters what exists" contract.
        from futures_bot.market_data.pg_store import PgMarketDataStore
        from futures_bot.research.pg_trade_store import PgTradeStore

        if not args.skip_market_data:
            PgMarketDataStore(dest_engine).ensure_schema()
        if not args.skip_research:
            PgTradeStore(dest_engine).ensure_schema()

    market_data_results: dict[str, tuple[int, int]] = {}
    research_results: dict[str, tuple[int, int]] = {}

    if not args.skip_market_data:
        try:
            market_data_results = migrate_market_data(market_data_db_path, dest_engine, dry_run=dry_run)
        except FileNotFoundError as exc:
            print(f"Skipping market_data.db: {exc}", file=sys.stderr)
        else:
            _print_report(f"market_data.db ({market_data_db_path})", market_data_results, dry_run=dry_run)

    if not args.skip_research:
        try:
            research_results = migrate_research(research_db_path, dest_engine, dry_run=dry_run)
        except FileNotFoundError as exc:
            print(f"Skipping research.db: {exc}", file=sys.stderr)
        else:
            _print_report(f"research.db ({research_db_path})", research_results, dry_run=dry_run)

    if dry_run:
        print("\nDry run complete. Re-run with --yes to actually migrate.")
        return 0

    print("\nVerifying row counts (source <= destination for every table)...")
    from futures_bot.db.research_schema import (
        client_import_fills as r_client_import_fills, client_open_lots as r_client_open_lots,
        client_profiles as r_client_profiles, config_deployments as r_config_deployments,
        experiments as r_experiments, import_history as r_import_history, import_staging as r_import_staging,
        jobs as r_jobs, ml_models as r_ml_models, model_deployments as r_model_deployments,
        optimization_trials as r_optimization_trials, reports as r_reports, runs as r_runs, trades as r_trades,
    )
    from futures_bot.db.schema import active_contracts as m_active_contracts, bars as m_bars
    from futures_bot.db.schema import contract_rolls as m_contract_rolls, gaps as m_gaps, sync_runs as m_sync_runs

    table_lookup = {
        "bars": m_bars, "sync_runs": m_sync_runs, "gaps": m_gaps,
        "active_contracts": m_active_contracts, "contract_rolls": m_contract_rolls,
        "trades": r_trades, "optimization_trials": r_optimization_trials, "runs": r_runs, "reports": r_reports,
        "jobs": r_jobs, "experiments": r_experiments, "ml_models": r_ml_models,
        "model_deployments": r_model_deployments, "client_profiles": r_client_profiles,
        "import_staging": r_import_staging, "client_import_fills": r_client_import_fills,
        "client_open_lots": r_client_open_lots, "import_history": r_import_history,
        "config_deployments": r_config_deployments,
    }
    all_results = {**market_data_results, **research_results}
    ok = _verify_row_counts(all_results, dest_engine, table_lookup)
    if not ok:
        print("\nVERIFICATION FAILED: destination has fewer rows than the source for at least one table.", file=sys.stderr)
        return 1
    print("\nMigration complete and verified.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
